import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { getCoinPrice } from '../core/fetch/coinGecko';
import { WalletSelectorContextProvider } from '../core/near/WalletSelectorContext';
import Content from '../components/Content';

export async function getServerSideProps() {
  const result = await getCoinPrice('near', 'eur');

  return {
    props: {
      price: result.near.eur,
    },
  };
}

export default function Web({ price }: { price: string }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Near Split</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Near ({price})
        </h1>
        <WalletSelectorContextProvider>
          <Content />
        </WalletSelectorContextProvider>
      </main>
    </div>
  );
}
